name: sptk
channels:
  - conda-forge
  - defaults
dependencies:
  - click=8.1
  - ipykernel=6.17
  - matplotlib=3.6.2
  - numpy=1.23.5
  - pandas=1.5.2
  - pillow=9.3.0
  - pip
  - python=3.10.8
  - scikit-learn=1.1.3
  - scipy=1.9.3
  - seaborn=0.12.2
  - statsmodels=0.13.2
  - tabulate=0.8.10
  - tabulate
  - spectral
  - plotnine
  - xgboost=0.72.1
  - lightgbm=2.1.2
  - cvxopt
  - pip:
      - pysptools=0.15.0
